### PR TITLE
Update Apps to use V2 API

### PR DESCRIPTION
**Pull request by vzDevelopment**
The V1 Fn Server API is no longer supported. Therefore, make a start on migrating the UI over to the V2 API. This commit migrates the App functionality over and means users can now add/delete/edit apps.

This contributes to: #52, fnproject/fn#1347, fnproject/fn_go#31, and fnproject/fn#1258.

There's still lots to do, but I want to keep the PRs small and easy to review.

### CODE REVIEW

**Comment by vzDevelopment** [comment]
N.b. I have [done futher work](https://github.com/vzDevelopment/ui/commit/cb40458ce8b2ddc25e246b490eafc3ac9f776c54) on migrating away from the V1 API. Did you want to review both these changes and the additional work I've done together or would you rather do them seperately? 

Currently I have opted to keep the seperate and will wait for this to be merged before creating a PR with the additional changes - my thinking is by keeping them seperate then the PRs are smaller and easier to review. However, let me know if it's easier for you to do them all at once.

**Comment by vzDevelopment** [comment]
I've also fixed the charts [here](https://github.com/vzDevelopment/ui/commits/bugfix/52-fix_metrics). However, this has tonnes of changes in so will raise a seperate PR once this is merged as per my note above.

**Comment by rdallman** [comment]
I get a 404 after clicking on an app from the home screen. but this fixes the home screen, woo. thank you for fixing this stuff up, feel free to post more PRs I can try to rifle through them, anything is an improvement!

**Comment by vzDevelopment** [comment]
Yup the 404 is fixed in https://github.com/fnproject/ui/pull/57#issuecomment-483302825 😀. I'll create a PR for that and the metrics now. I'll do both the metrics and the app details page at the same time (sorry it's going to be a bit of a monster PR).

**Pull request merged**
