### PR TITLE
readme updates

### PR DESCRIPTION
**Pull request by carimura**

### CODE REVIEW

**Comment by carimura** [comment]
@vzDevelopment do you mind adding a review so it clears the review check? thanks

**Comment by vzDevelopment** [comment]
Hi @carimura, I don't think I have write access which is why it isn't working. If I hover over the ticket where I have tried to review the code, it says:

> Only reviews by reviewers with write access count toward mergeability

Screen Shot 2019-04-28 at 12 24 39

**Comment by zootalures** [comment]
Approved

**Comment by carimura** [comment]
ah ok.. thanks @vzDevelopment and @zootalures

**Pull request merged**
