### PR TITLE
Fix GitHub spelling

### PR DESCRIPTION
**Pull request by friederbluemle**
Just a minor typo fix `Github` -> `GitHub`

### CODE REVIEW

**Comment by treeder** [comment]
Waiting on CLA integration for PR's before we can merge... :( . coming soon.

**Comment by friederbluemle** [comment]
@treeder Any updates on CLA integration? Thanks :)
I just rebased this branch.

**Comment by carimura** [comment]
@friederbluemle sorry for delay. We ran into some blocks on our end so for now the only way to sign the CLA is through this method: http://www.oracle.com/technetwork/community/oca-486395.html

Once signed, we'll merge this PR.

Thanks again and sorry for the delays....

**Comment by carimura** [comment]
this one is simple enough we can merge... CLA for future commits please.

**Comment by friederbluemle** [comment]
Thanks @carimura @treeder 👍

**Comment by carimura** [comment]
@friederbluemle you can sign it using a digital signature mechanism like mac preview --> tools -> annotate --> signature (if you're on a Mac) and email it. That said, the work to modernize this to a real digital signature is mostly done we're just going through approvals which takes awhile unfortunately.

**Comment by friederbluemle** [comment]
Thanks @carimura! I signed and emailed the document.

**Pull request merged**
